import asyncio
import shutil
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np
from tts_plugin_bridge.protocol import TTSConnector, TTSRequest, TTSResponse


class KokoroConnector(TTSConnector):
    """Kokoro-TTS Engine Connector.

    This connector provides an interface to the Kokoro-82M TTS model,
    supporting multiple languages and voices with an efficient pipeline caching strategy.
    """

    ENGINE_NAME = "kokoro"
    SUPPORTED_PARAMS = ["voice", "speed", "lang_code"]
    SAMPLE_RATE = 24000  # Kokoro default sample rate

    def __init__(self, model_path: Optional[str] = None, default_voice: str = "af_heart"):
        self.model_path = Path(model_path) if model_path else Path("models/kokoro-v1_0.pth")
        self.default_voice = default_voice
        self._pipelines: Dict[str, Any] = {}

    async def is_available(self) -> bool:
        """Check if the engine is available.

        Checks for:
        1. espeak-ng executable in the system path.
        2. Existence of the model file.
        """
        if not shutil.which("espeak-ng"):
            return False
        if not self.model_path.exists():
            return False
        return True

    async def _get_pipeline(self, lang_code: str = "a") -> Any:
        """Get or create a KPipeline for the given language code.

        Implements caching to avoid reloading the model for the same language.

        Args:
            lang_code: Language code (e.g., 'a' for American English, 'j' for Japanese).

        Returns:
            The KPipeline instance for the specified language.

        Raises:
            ImportError: If the kokoro package is not installed.
            RuntimeError: If KPipeline initialization fails.
        """
        if lang_code not in self._pipelines:
            try:
                from kokoro import KPipeline

                self._pipelines[lang_code] = KPipeline(
                    lang_code=lang_code,
                    model=str(self.model_path),
                )
            except ImportError:
                raise ImportError("kokoro package not installed")
            except Exception as e:
                raise RuntimeError(f"Failed to initialize KPipeline: {e}") from e
        return self._pipelines[lang_code]

    def _run_synthesis(self, pipeline: Any, text: str, voice: str, speed: float) -> np.ndarray:
        """Synchronous wrapper for the Kokoro synthesis process.

        Args:
            pipeline: The KPipeline instance used for synthesis.
            text: The input text to synthesize.
            voice: The voice ID to use.
            speed: The speech rate multiplier.

        Returns:
            A concatenated numpy array containing the generated audio.

        Raises:
            ValueError: If no audio chunks are generated by the pipeline.
        """
        generator = pipeline(text, voice=voice, speed=speed)
        audio_chunks = [audio for _, _, audio in generator]
        if not audio_chunks:
            raise ValueError("No audio generated")
        return np.concatenate(audio_chunks)

    def _numpy_to_wav(self, audio_np: np.ndarray) -> bytes:
        """Convert a numpy array to WAV bytes using soundfile.

        Args:
            audio_np: The audio data as a numpy array.

        Returns:
            The audio data formatted as WAV bytes.
        """
        import io

        import soundfile as sf

        buffer = io.BytesIO()
        sf.write(buffer, audio_np, self.SAMPLE_RATE, format="WAV")
        return buffer.getvalue()

    async def synthesize(self, req: TTSRequest) -> TTSResponse:
        """Synthesize text to speech using the Kokoro model.

        Args:
            req: The TTS request containing text, speed, and optional voice/lang_code.

        Returns:
            A TTSResponse indicating success (with audio data) or failure.
        """
        try:
            lang_code = req.extra.get("lang_code", "a")
            pipeline = await self._get_pipeline(lang_code)
            voice = req.extra.get("voice", self.default_voice)

            # Run blocking synthesis in a thread
            audio_np = await asyncio.to_thread(
                self._run_synthesis, pipeline, req.text, voice, req.speed
            )

            # Run blocking WAV conversion in a thread
            wav_bytes = await asyncio.to_thread(self._numpy_to_wav, audio_np)

            return TTSResponse.ok(audio_data=wav_bytes)

        except ImportError as e:
            return TTSResponse.fail(f"kokoro package not installed: {e}")
        except FileNotFoundError as e:
            return TTSResponse.fail(f"Model file not found: {e}")
        except ValueError as e:
            return TTSResponse.fail(f"Synthesis failed: {e}")
        except RuntimeError as e:
            return TTSResponse.fail(f"Runtime error during synthesis: {e}")
        except Exception as e:
            return TTSResponse.fail(f"Unexpected error during synthesis: {type(e).__name__}: {e}")

    async def close(self) -> None:
        """Clean up loaded pipelines to prevent memory leaks."""
        self._pipelines.clear()
